using System;
using TMPro;
using UnityEngine;

public class FlashCardsAnswerContainers : MonoBehaviour
{
    private void Awake()
    {
        //Subscribe to nextQuestion event.
        GameManager.instance.nextQuestion += ChangeSet;
    }

    // reference to each answer button texts
    [SerializeField] TextMeshProUGUI[] text;

    [Serializable]
    public class AnswerSets //change name
    {
        public string[] answer;
    }

    [SerializeField] public AnswerSets[] sets;

    // Changes set of answers
    public void ChangeSet(int x) //x is the number generated by GameManager
    {
        for (int i = 0; i < text.Length; i++)
        {
            text[i].text = sets[x].answer[i];
        }
    }

}
